FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /backend
RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    pkg-config \
    default-libmysqlclient-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
COPY ./apps/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./apps/backend/ .
RUN chmod +x /backend/entrypoint.sh
EXPOSE 8888
CMD ["/backend/entrypoint.sh"]