# Generated by Django 6.1.1 on 2026-10-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.CharField(db_index=True, max_length=50)),
                ('id_product', models.CharField(db_index=True, max_length=50)),
                ('p_name', models.CharField(blank=True, max_length=255)),
                ('p_qnt', models.IntegerField()),
                ('p_prc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_address', models.CharField(max_length=255)),
                ('p_status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('p_od', models.DateTimeField(auto_now_add=True)),
                ('p_sd', models.DateTimeField(blank=True, null=True)),
                ('p_dd', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
